language: java
jdk:
- oraclejdk8
script: cd VoteResultsModel && npm test && cd VoteResultsREST && npm test && cd VoteResultsWeb && npm test 
after_success:
  - bash <(curl -s https://codecov.io/bash)
